name: root_flutter_wrapper
description: Wrapper to point CI/analyzers to the actual Flutter app in a subdirectory.
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
